import Head from 'next/head';
import { Providers } from '../components/Providers';
import '../styles/globals.css';

function MyApp({ Component, pageProps }: any) {
  return (
    <Providers>
      <Head>
        <title>Life organizer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/custom_favicon.ico" />
        {/*
          <link rel="icon" type="image/png" sizes="16x16" href="/custom_favicon.ico" />
          <link rel="apple-touch-icon" sizes="180x180" href="/custom_favicon.ico" />
          <link rel="manifest" href="/site.webmanifest" />
          <link rel="mask-icon" href="/custom_favicon.ico" color="#5bbad5" />
          <meta name="msapplication-TileColor" content="#da532c" />
          <meta name="theme-color" content="#ffffff" />
        */}
      </Head>
      <Component {...pageProps} />
    </Providers>
  );
}

export default MyApp;
